sensor_kit_base_link:
  camera0/camera_link:
    x: 0.075
    y: 0.25
    z: -0.13
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  velodyne_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  gnss_link:
    x: -0.697
    y: -0.315
    z: -0.05
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  tamagawa/imu_link:
    x: -0.697
    y: -0.315
    z: -0.05
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  
